FROM node:latest

RUN mkdir -p /var/www/html

WORKDIR /var/www/html

CMD ["sleep", "infinity"]

# COPY . .

# RUN npm i -g npm@latest && npm i && npm update && npm run build

# CMD [ "node", ".output/server/index.mjs"]
